### ISSUE TITLE
Import job adding information in docker path

### ISSUE THREAD

**Issue by cshamis** [ngageoint/seed-silo#28] opened 2019-07-08 23:25 UTC
Docker published to: myrepo.com/seedthing:1.0.0_1.0.0

Scale inserting as:
myrepo.com/other-org/seedthing:1.0.0_1.0.0

Not sure where the "other-org" string is coming from.  It isn't present in the manifest.  Don't know if it's silo or the UI that might be getting confused.

**Comment by emimaesmith** [comment] 2019-07-09 13:42
This is not a UI or Scale issue. The silo registry list was updated to include a similar registry to one that was already there - just with the 'other-org' organization specified. So the registry table included:

| Name | URL | Organization
| --- | --- | --- |
| My Repo | https:\\myrepo.com | |
| My Repo | myrepo.com | other-org |

This could be a bug in silo why all of the original registry images are now being reported as both myrepo.com/image-seed and myrepo.com/other-org/image-seed.

**Comment by JohnPTobe** [comment] 2019-07-09 14:59
Like Emily said, this was caused by the registry with the invalid org. Closing this issue.

**Closed by JohnPTobe** 2019-07-09 14:59 UTC
Labels: bug
